### ISSUE TITLE
PyPi Release

### ISSUE THREAD

**Issue by vwxyzjn** [wookayin/expt#17]
Hi @wookayin, any chance you could make a release on commit https://github.com/wookayin/expt/commit/ab538316b3e33c7c6acda16da68cbc6e9f05d49a? I am trying to make a pypi release at openrlbenchmark, and it does not allow me use expt's github link as the dependency.

**Comment by wookayin** [comment]
Is there any specific commit or new feature you are relying on in your project *past* the v0.4.1 release, if any, so I can consider a backport release v0.4.2? That specific commit seems the very before the rust extension is introduced.

**Comment by vwxyzjn** [comment]
That's just the latest commit that is still installable without rust. If there is another more appropriate commit candidate, feel free to use that :)

**Comment by vwxyzjn** [comment]
FWIW, `0cd947f8c5fc66598e578ce8a394c5f522f060bd` commit has worked for me, too.

**Comment by wookayin** [comment]
So what I was wondering is if using the stable release of expt on PyPI (expt==0.4.1) is an option for you. Have you tried v0.4.1 by any chance? I don't remember any particular critical bugfix since then.

I am making a lot of changes on a 0.5.x version (including some breaking changes), some of which I'm not sure yet I'm fully confident about them so I would be a bit hesitant about making hasty releases.

**Comment by wookayin** [comment]
As a last resort, making a pre-release (alpha version) would be another option -- without the rust extension.

**Comment by vwxyzjn** [comment]
Oh actually the existing release worked! I think previously I was working with plotting the median curve, but for this release I am not using it.

**Comment by wookayin** [comment]
Yes, but the median curve #5 is included in v0.4.0.

**Comment by vwxyzjn** [comment]
Ah I see. Then all is good with me. Sorry for the extra trouble.
